### ISSUE TITLE
Release 3.7.0 does not work with pyarrow 7.0.0

### ISSUE THREAD

**Issue by vinvinod** [aws/aws-sdk-pandas#2707]
### Describe the bug

The new release 3.7.0 has the dependecy on pyarrow set as `pyarrow = ">=7.0.0"` in [pyproject.toml](https://github.com/aws/aws-sdk-pandas/blob/5f36e61c8b694adb2c4604b42a4343a3a6a0173c/pyproject.toml#L42)

However, since https://github.com/aws/aws-sdk-pandas/pull/2674, `decryption_properties` argument of `pyarrow.parquet.ParquetFile` class is being used which is not supported by `pyarrow >= 8.0.0`.

### How to Reproduce

Install the versions:
```
pip install awswrangler==3.7.0 pyarrow==7.0.0
```

Code:

```python
import pyarrow
import awswrangler

from awswrangler.s3._read_parquet import _pyarrow_parquet_file_wrapper

assert pyarrow.__version__ == "7.0.0"
assert awswrangler.__version__ == "3.7.0"

_pyarrow_parquet_file_wrapper("dummy")

```

Result:

```bash
> python test_pyarrow.py
Traceback (most recent call last):
  File "/Users/vinod/projects/my_project/test_pyarrow.py", line 9, in <module>
    _pyarrow_parquet_file_wrapper("dummy")
  File "/Users/vinod/projects/my_project/.venv/lib/python3.9/site-packages/awswrangler/s3/_read_parquet.py", line 62, in _pyarrow_parquet_file_wrapper
    return pyarrow.parquet.ParquetFile(
TypeError: __init__() got an unexpected keyword argument 'decryption_properties'
```

### Expected behavior

I expect that `TypeError` is not raised in the constructor of `pyarrow.parquet.ParquetFile`.

### OS

Mac

### Python version

3.9.13

### AWS SDK for pandas version

3.7.0

**Comment by jaidisido** [comment]
Thanks for raising this. The only reason we supported such a wide range in pyarrow (7 to 15) was because some dependencies required pyarrow 7 and below. It seems that is not the case anymore. 

@kukushking and @LeonLuttenberger I believe it's time to cap pyarrow to a higher version. I  am testing with 8+ in #2709 but perhaps we should go for even higher, wdyt?
