### ISSUE TITLE
Import error after upgrading to Python 3.11 Managed Layer

### ISSUE THREAD

**Issue by flowtrader2016** [aws/aws-sdk-pandas#2423]
### Describe the bug

After upgrading to the Python Managed Layer 3.11 on AWS Lambda, an import error is occurring when attempting to use the `aws-sdk-pandas` package.

Error when using:

`arn:aws:lambda:us-east-2:336392948345:layer:AWSSDKPandas-Python311-Arm64:1`

I did not previously get this issue using:

`arn:aws:lambda:us-east-2:336392948345:layer:AWSSDKPandas-Python310-Arm64:2`

### How to Reproduce

**To Reproduce**
1. Upgrade to Python Managed Layer 3.11 on AWS Lambda from 3.10
2. Attempt to invoke the Lambda.
3. The following error message is displayed:

```json
{
  "errorMessage": "Unable to import module 'handler': cannot import name 'DEPRECATED_SERVICE_NAMES' from 'botocore.docs' (/var/task/botocore/docs/__init__.py)",
  "errorType": "Runtime.ImportModuleError",
}
```
### Expected behavior

The Lambda function should run successfully without any import errors.

### OS

AWS Lambda

### Python version

3.11

### AWS SDK for pandas version

3.3.0

**Comment by kukushking** [comment]
Hi @flowtrader2016 

> Upgrade to Python Managed Layer 3.11 on AWS Lambda from 3.10

You should only use 3.11 layers with Python 3.11 lambdas. Make sure you upgrade the runtime as well. 

I also ran a quick check and I'm not able to reproduce this with Python 3.11 lambda running Python 3.11 layer, and Python 3.10 lambda running 3.10 so layers should be fine as long as they're used with the corresponding runtime.

**Comment by flowtrader2016** [comment]
Hi,

Can confirm I am using the 3.11 layer with Python 3.11 lambda.  For additional context the requirements.txt contains:

```
datetime
oandapyV20
pytz
s3fs
requests
notion-client
multiprocess
tabulate
```

As mentioned this works well with python/lambda layer <= 3.10.  Appreciate any feedback as to how I might fix this. 

Thanks

**Comment by kukushking** [comment]
Can you share the stack trace or the error / lambda logs?

```
"Unable to import module 'handler': cannot import name 'DEPRECATED_SERVICE_NAMES' from 'botocore.docs' (/var/task/botocore/docs/__init__.py)"
```
AWS SDK for pandas does not import from `botocore.docs`. Is there a chance this is caused by user code rather than the layer?

**Comment by kamami** [comment]
Why is this closed? I have the same error after upgrading from 3.8 to 3.11!

**Comment by LeonLuttenberger** [comment]
Can you print out which versions of `boto3` and `botocore` you are using?I have not been able to reproduce this error either, and my Python 3.11 Lambda was using `boto3==1.27.1` and `botocore==1.30.1`.

You can use the following code to print these values:
```python
import boto3
import botocore

...

print("boto3 version:", boto3.__version__)
print("botocore version:", botocore.__version__)
```

It looks like this is likely related to [this issue](https://github.com/boto/boto3/issues/3648) in boto3.
